// ⚠️ ไฟล์นี้ถูกสร้างอัตโนมัติโดย scripts/build-assets.sh — อย่าแก้ด้วยมือ
// มีรูปเพิ่ม? วางไฟล์ในโฟลเดอร์งานแล้วรัน: bash scripts/build-assets.sh

// ตัวละคร (2-Production/5.1 Characters/v2-characters/)
const AVATAR = new Set([
  "build-broroma",
  "build-leo-residence",
  "build-nps-plus",
  "build-sirayooth",
  "grow-forth-smart",
  "grow-kbank-wealth",
  "grow-profess-rent",
  "grow-tower-tactic",
  "live-aday-fresh",
  "live-damrong",
  "live-pchw",
  "live-sirichai",
  "live-vejpong",
  "live-yoksod",
  "make-foilmaster",
  "make-mastercrafts",
  "make-pc-foil",
  "make-quality-flexpack",
  "move-aps-commerce",
  "move-atn",
  "move-ch-pattana",
  "move-tpi",
  "thrive-joyous",
  "thrive-rebalance",
  "thrive-winds",
]);

// รูปเจ้าของตัวจริง (1-Teams/**/face*)
const OWNER = new Set([
  "build-absolute65",
  "build-broroma",
  "build-leo-residence",
  "build-nps-plus",
  "build-sirayooth",
  "build-sp-engineering",
  "grow-forth-smart",
  "grow-kbank-sme",
  "grow-kbank-wealth",
  "grow-profess-rent",
  "grow-tower-tactic",
  "live-aday-fresh",
  "live-damrong",
  "live-pchw",
  "live-sirichai",
  "live-vejpong",
  "live-yoksod",
  "make-foilmaster",
  "make-mastercrafts",
  "make-pc-foil",
  "make-quality-flexpack",
  "move-aps-commerce",
  "move-atn",
  "move-ch-pattana",
  "move-jaturong",
  "move-tpi",
  "thrive-joyous",
  "thrive-leviya",
  "thrive-rebalance",
  "thrive-winds",
]);

// โลโก้กิจการ (1-Teams/**/logo*)
const LOGO = new Set([
  "build-absolute65",
  "build-broroma",
  "build-leo-residence",
  "build-nps-plus",
  "build-sirayooth",
  "build-sp-engineering",
  "grow-forth-smart",
  "grow-kbank-sme",
  "grow-kbank-wealth",
  "grow-profess-rent",
  "grow-tower-tactic",
  "live-aday-fresh",
  "live-damrong",
  "live-pchw",
  "live-sirichai",
  "live-vejpong",
  "live-yoksod",
  "make-foilmaster",
  "make-mastercrafts",
  "make-quality-flexpack",
  "move-aps-commerce",
  "move-atn",
  "move-ch-pattana",
  "move-jaturong",
  "move-tpi",
  "thrive-joyous",
  "thrive-leviya",
  "thrive-rebalance",
  "thrive-winds",
]);

export const avatarSrc = (id) => (AVATAR.has(id) ? `/avatar/${id}.webp` : null);
export const ownerSrc = (id) => (OWNER.has(id) ? `/owner/${id}.webp` : null);
export const logoSrc = (id) => (LOGO.has(id) ? `/logo/${id}.webp` : null);
export const heroSrc = (team) => `/hero/${team}.webp`;
