// สร้าง seed.sql จาก members.json + teams
// รัน: node db/gen-seed.mjs > db/seed.sql
import { readFileSync } from "node:fs";

const members = JSON.parse(readFileSync(new URL("./members.json", import.meta.url), "utf8"));

const TEAMS = [
  ["BUILD", "สายก่อสร้าง-อุตสาหกรรม", "#D97706", "รากฐานที่แข็งแรงของทุกธุรกิจ", 1],
  ["MAKE", "สายผลิต-แพ็กเกจจิ้ง", "#7C3AED", "เปลี่ยนของธรรมดาให้เป็นของพรีเมียม", 2],
  ["MOVE", "สายขนส่ง-โลจิสติกส์", "#2563EB", "ทุกอย่างต้องถึงที่หมาย ตรงเวลา", 3],
  ["GROW", "สายการเงิน-บริการธุรกิจ", "#059669", "ตัวเลขที่เคยร่วง จะกลับมาพุ่งขึ้นอีกครั้ง", 4],
  ["LIVE", "สายอาหาร-เกษตร", "#DB2777", "ความสดจากต้นทาง ถึงมือคุณ", 5],
  ["THRIVE", "สายสุขภาพ-ความงาม", "#0D9488", "ดูแลคน ให้กลับมาเป็นตัวเองที่ดีที่สุด", 6],
];

// คลิปที่ generate ไปแล้ว (Higgsfield CDN)
const CDN = "https://d8j0ntlcm91z4.cloudfront.net/user_3FvAUpXpCnZUma0p4ZCgNFe1CGD/";
const CLIPS = [
  ["live-aday-fresh", 1, "91ac575e-da0a-43ce-b360-3f17bc1c47f9", "hf_20260804_091327_91ac575e-da0a-43ce-b360-3f17bc1c47f9.mp4", "approved"],
  ["live-damrong", 1, "e8a56b64-7624-4803-aea2-e299906f393c", "hf_20260804_090710_e8a56b64-7624-4803-aea2-e299906f393c.mp4", "approved"],
  ["live-yoksod", 1, "6026d68d-e430-4fda-bdaf-853b87198a99", "hf_20260804_092025_6026d68d-e430-4fda-bdaf-853b87198a99.mp4", "approved"],
  ["live-sirichai", 1, "cdca1e47-bedf-4d57-ab74-f73f8360b9a8", "hf_20260804_092025_cdca1e47-bedf-4d57-ab74-f73f8360b9a8.mp4", "approved"],
  ["live-vejpong", 1, "6d389826-7215-4c78-bd30-2999d6a01884", "hf_20260804_092025_6d389826-7215-4c78-bd30-2999d6a01884.mp4", "approved"],
  ["live-pchw", 1, "f211731b-3893-4c18-b222-414a45d81d7b", "hf_20260804_092025_f211731b-3893-4c18-b222-414a45d81d7b.mp4", "approved"],
  ["make-pc-foil", 1, "fb35373c-1877-4318-bb33-72dd7c843d2b", "hf_20260804_093400_fb35373c-1877-4318-bb33-72dd7c843d2b.mp4", "rejected"],
  ["make-foilmaster", 1, "a71af033-df4f-431c-9e4f-072a3514f152", "hf_20260804_093400_a71af033-df4f-431c-9e4f-072a3514f152.mp4", "rejected"],
  ["make-quality-flexpack", 1, "d427d2a3-eb27-4960-8536-83e4e981c1b9", "hf_20260804_093400_d427d2a3-eb27-4960-8536-83e4e981c1b9.mp4", "rejected"],
  ["make-mastercrafts", 1, "fe53d192-9013-4531-bf26-621dbf1f6daa", "hf_20260804_093400_fe53d192-9013-4531-bf26-621dbf1f6daa.mp4", "rejected"],
  ["make-pc-foil", 2, "70b378f9-e2a2-459e-8fd6-8ca16ea14d4e", "hf_20260804_094052_70b378f9-e2a2-459e-8fd6-8ca16ea14d4e.mp4", "draft"],
  ["make-foilmaster", 2, "8e6609b4-3637-4352-8db4-37149b03eae6", "hf_20260804_094051_8e6609b4-3637-4352-8db4-37149b03eae6.mp4", "draft"],
  ["make-quality-flexpack", 2, "85e9ee84-d0e3-494b-a1d5-be65debf359a", "hf_20260804_094051_85e9ee84-d0e3-494b-a1d5-be65debf359a.mp4", "draft"],
  ["make-mastercrafts", 2, "25a0149a-f556-4ded-ad25-5f70cdb1107f", "hf_20260804_094051_25a0149a-f556-4ded-ad25-5f70cdb1107f.mp4", "draft"],
];

const SCRIPT = [
  ["style", "🎨 สไตล์ภาพที่ล็อกไว้ (ใช้กับทุกคลิป)",
`• คนใช้รูปจริง (photoreal) — ไม่ใช่การ์ตูน
• โลกแบบอนาคตอันใกล้ (near-future Thailand)
• เกรดสีธรรมชาติ หม่นๆ (natural muted cinematic) ไม่จัดจ้าน
• แสงนุ่ม volumetric, ชัดตื้น, กล้องแฮนด์เฮลด์นิดๆ
• แต่ละคนต้องมี signature move ที่มาจากจุดเด่นธุรกิจจริง — ห้ามซ้ำกัน ห้ามวิ่งทุกฉาก
• เว้นมุมขวาบน + หนึ่งในสามล่างซ้ายให้ว่าง สำหรับใส่โลโก้และข้อความไทยตอนตัดต่อ
• ห้าม AI วาดตัวอักษรเอง (ภาษาไทยเพี้ยนเสมอ) — ปิดซับไตเติลด้วย`, 1],
  ["voice", "🎙 เสียงบรรยาย",
`• ใช้เสียง Gideon (ElevenLabs) ทุ้ม แหบ ขรึม แนว movie trailer
• เทคนิคให้ AI อ่านไทยชัด: เว้นวรรคระหว่างคำ + ใส่ ... เป็นจังหวะหยุด + ใส่ ! เพื่อเน้น
• ตัวอย่าง: "ในโลก... ที่ ธุรกิจ ต้องเจอกับ ต้นทุน ที่พุ่งสูง!"`, 2],
  ["structure", "🎬 โครงเรื่อง VTR (v3)",
`1. ฉากปัญหาของทั้ง 6 สาย ติดๆ กันตอนเปิด
2. intro กลุ่ม (สั้นๆ) ก่อนเข้าแต่ละทีม
3. แนะนำทีละกิจการ คนละ 5-8 วินาที — ครบทั้ง 30 คน
4. ไม่มีคลิปเปิดตัวหัวหน้าทีมแยก (หัวหน้าอยู่ในคิวปกติ)
5. Finale รวมทุกคน`, 3],
  ["problem-build", "😰 ฉากปัญหา — BUILD", "ไซต์งานที่หยุดนิ่ง เครื่องจักรดับ ไฟดับทั้งโรงงาน ต้นทุนพลังงานพุ่ง", 10],
  ["problem-make", "😰 ฉากปัญหา — MAKE", "สินค้าดีแต่แพ็กเกจจิ้งไม่ดึงดูด วางบนชั้นแล้วไม่มีใครหยิบ ของเสียหายระหว่างขนส่ง", 11],
  ["problem-move", "😰 ฉากปัญหา — MOVE", "ลานรถขนส่งที่รถจอดนิ่ง ตู้คอนเทนเนอร์กองไม่ได้ออก ของติดด่าน ส่งไม่ทัน", 12],
  ["problem-grow", "😰 ฉากปัญหา — GROW", "กราฟยอดขายที่ร่วงลง เงินหมุนไม่ทัน หาคนทำงานไม่ได้", 13],
  ["problem-live", "😰 ฉากปัญหา — LIVE", "ของสดที่เสียก่อนถึงมือลูกค้า ตลาดเงียบ ราคาผลผลิตตก", 14],
  ["problem-thrive", "😰 ฉากปัญหา — THRIVE", "คนที่เหนื่อยล้า ปวดเรื้อรัง หมดความมั่นใจในตัวเอง", 15],
];

const q = (v) => (v === null || v === undefined || v === "" ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const b = (v) => (v ? "true" : "false");

const out = [];
out.push("-- generated by db/gen-seed.mjs — do not edit by hand");
out.push("begin;");

out.push("\n-- teams");
for (const [k, n, c, t, s] of TEAMS)
  out.push(`insert into teams(key,name_th,color,tagline,sort_order) values (${q(k)},${q(n)},${q(c)},${q(t)},${s}) on conflict (key) do update set name_th=excluded.name_th,color=excluded.color,tagline=excluded.tagline;`);

out.push("\n-- members");
for (const m of members) {
  out.push(
    `insert into members(id,team,sort_order,code,company_th,company_en,owner_name,nickname,gender,is_leader,business,highlight,benefit,products,scene_idea,dialogue_th,contact,note) values (` +
      [q(m.id), q(m.team), m.sort_order, q(m.code), q(m.company_th), q(m.company_en), q(m.owner_name), q(m.nickname), q(m.gender), b(m.is_leader), q(m.business), q(m.highlight), q(m.benefit), q(m.products), q(m.scene_idea), q(m.dialogue_th), q(m.contact), q(m.note)].join(",") +
      `) on conflict (id) do nothing;`
  );
  for (const [kind, has] of Object.entries(m.assets || {}))
    out.push(`insert into assets(member_id,kind,has_it) values (${q(m.id)},${q(kind)},${b(has)}) on conflict (member_id,kind) do update set has_it=excluded.has_it;`);
}

out.push("\n-- clips ที่ generate ไปแล้ว");
for (const [mid, ver, job, file, st] of CLIPS)
  out.push(`insert into clips(member_id,version,job_id,video_url,status) values (${q(mid)},${ver},${q(job)},${q(CDN + file)},${q(st)});`);

out.push("\n-- script");
for (const [k, t, body, s] of SCRIPT)
  out.push(`insert into script_sections(key,title_th,body,sort_order) values (${q(k)},${q(t)},${q(body)},${s}) on conflict (key) do update set title_th=excluded.title_th, body=excluded.body;`);

out.push("\n-- ตั้ง status ตามคลิปที่มี");
out.push("update members m set status='approved' where exists (select 1 from clips c where c.member_id=m.id and c.status='approved');");
out.push("update members m set status='drafted' where status='todo' and exists (select 1 from clips c where c.member_id=m.id);");

out.push("commit;");
console.log(out.join("\n"));
